kernel: update to 3.18.21-rt19
And alter procedure to match new archlinuxarm images

diff --git a/kernel/README b/kernel/README
--- a/kernel/README
+++ b/kernel/README
@@ -6,9 +6,9 @@
 ##         Some steps are (mostly volontary) not complete.
 
 # Define some config environment variables
-KERN=3.18
-KERNSUB=9
-RT=5
+export KERN=3.18
+export KERNSUB=21
+export RT=19
 
 # Download kernel
 wget -c https://www.kernel.org/pub/linux/kernel/v3.x/linux-${KERN}.${KERNSUB}.tar.xz
@@ -28,14 +28,14 @@ cp sikula_bbb_rt_defconfig linux-${KERN}.${KERNSUB}/arch/arm/configs/
 # Copy Sikula DTS for BBB+IO2
 cp sikula_bbb_io2.dts linux-${KERN}.${KERNSUB}/arch/arm/boot/dts/
 
+# Patching DTS Makefile
+patch -d linux-${KERN}.${KERNSUB} -p1 < sikula_bbb_io2-dts-makefile.patch
+
 # Go to kernel directory
 cd linux-${KERN}.${KERNSUB}
 
 # Applying defconfig
 make ARCH=arm sikula_bbb_rt_defconfig
-
-# Patching DTS Makefile
-patch -p1 < ../sikula_bbb_io2-dts-makefile.patch
 
 # Compile kernel, modules and dtbs
 make ARCH=arm CROSS_COMPILE=archlinuxarm- zImage modules dtbs -j16
@@ -46,8 +46,9 @@ make ARCH=arm CROSS_COMPILE=archlinuxarm- zImage modules dtbs -j16
 ##################
 
 ## Notice: Environment variable $TARGET is supposed to be set with path to
-##         target rootfs (2nd partition on SD) while $BOOT is the path to
-##         target boot partition (1st partition on SD)
+##         target rootfs (mounted partition of SD).
+[ "$TARGET" == "" ] && echo "Error, TARGET is not defined"
+[ "$TARGET" == "" ] && exit 1
 
 # Copy kernel
 cp arch/arm/boot/zImage ${TARGET}/boot/zImage-sikula-rt
@@ -59,4 +60,4 @@ cp arch/arm/boot/dts/sikula_bbb_io2.dtb ${TARGET}/boot/dtbs/
 make ARCH=arm INSTALL_MOD_PATH=${TARGET}/ modules_install
 
 # Copy uEnv.txt (replace original)
-cp uEnv.txt ${BOOT}/uEnv.txt
+cp uEnv.txt ${TARGET}/boot/uEnv.txt
